tasks:
  - init: "wget https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tgz && \
           tar x Python-3.10.0.tgz && \
           cd Python-3.10.0 && \
           ./configure && \
           sudo make install && \
           rm -rf Python-3.10.0.tgz Python-3.10.0 && \
           alias python=python3.10 && \
           pip install -r requirements.txt
           exit 0"
    command: "echo 1"